services:
  - type: web
    name: agenticos-app
    env: node
    branch: main
    repo: ${RENDER_GIT_REPO}
    buildCommand: bun install
    startCommand: bun start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: RENDER_GIT_REPO
        sync: false

      - key: TWITTER_CLIENT_ID
        sync: false
      - key: TWITTER_CLIENT_SECRET
        sync: false

      - key: ENCRYPTION_KEY
        sync: false
      - key: ENCRYPTION_SALT
        sync: false
      - key: ENCRYPTION_IV
        sync: false

      - key: CHAINGPT_API_KEY
        sync: false

      - key: PASSWORD_AUTH
        sync: false
