name: Update Deploy Button

on:
  push:
    branches:
      - '**'  # This will trigger on all branches
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update README
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          BRANCH: ${{ github.ref_name }}
        run: |
          # Create the deployment URL
          DEPLOY_URL="https://render.com/deploy?repo=https://github.com/$REPO_OWNER/$REPO_NAME&branch=$BRANCH"
          
          # Update the README.md
          sed -i "s|https://render.com/deploy?repo=https://github.com/[^/]*/[^&]*&branch=[^)]*|$DEPLOY_URL|g" README.md
          
          # Commit and push changes
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update deployment button for branch: $BRANCH" || exit 0
          git push 