name: Update README

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update README
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          BRANCH: ${{ github.ref_name }}
        run: |
          # Update README.md with actual repository information
          sed -i "s|https://render.com/deploy?repo=https://github.com/OWNER/REPO&branch=BRANCH|https://render.com/deploy?repo=https://github.com/$REPO_OWNER/$REPO_NAME\&branch=$BRANCH|g" README.md
          
          # Commit and push changes
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update deployment button with current repository info" || exit 0
          git push 